### ISSUE TITLE
öneri

### ISSUE THREAD

**Issue by javav12** [isPique/Net-Strike#1]
# bu proje çok güzel ve tr de böyle proje yapan birilerini görmek güzel ama bazı önerilerim var

**1. help komutu eklenmeli
2. programın rootda olup olmadığı kontrol edilmeli
3. ayrıca bi yardım sayfası açılırsa güzel olur(dc de fln)**

basta dediğim gibi proje çok güzel ama daha gelistirile bilir

**Comment by isPique** [comment]
Teşekkür ederim dostum önerilerin için. Kullanıcının bilmesi gereken her şeyi "README.md" dosyasında anlattığım için help komutu eklemeye ihtiyaç duymamıştım ama evet yapılabilir. Programın root olarak çalışıp çalışmadığını kontrol etmek aklımdaydı onu en yaparım en kısa zamanda. Onun dışında bi dc sunucu açmayı düşünüyordum zaten ama gerek var mı bilemedim.

**Comment by javav12** [comment]
ben tesekür ederüm saolun (konuyu kapattım)
