### ISSUE TITLE
this does not work on raspberry pi or at all for me

### ISSUE THREAD

**Issue by Sheikh-Nightshader** [isPique/Net-Strike#2]
i updated everything after installing the requirements and it still says modules not found with useragent first it was fake useragent then i updated it. now when i am in root it says i must be root to run this. the same thing happened to be using nethunter kali this tool is broken

**Comment by isPique** [comment]
@Sheikh-Nightshader
> the same thing happened to be using nethunter kali this tool is broken

If you have at least the reading ability of a third grader, you can see under the Prerequisites section of the README file that I mentioned Windows or Linux operating systems are required to run this script.

However, if you have at least beginner-level coding skills, you can see the "Check for root" condition in the script and remove it.

You can try these too:

```bash
sudo pip3 install --upgrade scapy aiohttp fake-useragent
```

```bash
sudo apt-get install python3-scapy
```

```bash
sudo python3 NetStrike.py
```

**Comment by Sheikh-Nightshader** [comment]
Yup removing the root permission did it thanks. I feel dumb now but only took less than 10 sec to fix. I really thought this was broke or my permissions where. But this is happening on both nethunter and my raspberry pi. Thanks again ill give it a run my friend said this is pretty kool and now i can tell him how i think

**Comment by Sheikh-Nightshader** [comment]
Ok yes Nice works great. Thanks again. Problem solved
